use std::{fs, io};

use namako_engine::{
    StatsWriter as _, World, codegen::AssertOutcome, gherkin::Step, given, then, when,
};

use tempfile::TempDir;

#[derive(Debug, World)]
#[world(init = Self::new, mut_ctx = MyWorldMut<'a>, ref_ctx = MyWorldRef<'a>)]
pub struct MyWorld {
    foo: i32,
    dir: TempDir,
}

impl MyWorld {
    fn new() -> io::Result<Self> {
        Ok(Self {
            foo: 0,
            dir: TempDir::new()?,
        })
    }
}

// Context wrapper types
// StepContext impls are auto-generated by #[derive(World)]!
pub struct MyWorldMut<'a>(&'a mut MyWorld);

#[derive(Clone, Copy)]
pub struct MyWorldRef<'a>(&'a MyWorld);

impl<'a> MyWorldMut<'a> {
    fn new(world: &'a mut MyWorld) -> Self {
        Self(world)
    }
}
impl<'a> MyWorldRef<'a> {
    fn new(world: &'a MyWorld) -> Self {
        Self(world)
    }
}

#[given("non-regex")]
fn test_non_regex_sync(w: MyWorldMut) {
    w.0.foo += 1;
}

#[given("non-regex async")]
async fn test_non_regex_async(w: MyWorldMut, #[step] ctx: &Step) {
    assert_eq!(ctx.value, "non-regex async");

    w.0.foo += 1;
}

#[given("{word} is not {word}")]
fn test_foo_is_not_bar(_w: MyWorldMut, _foo: String, _bar: String) {}

#[given("{word} is {int}")]
#[when(r"{word} is {int}")]
async fn test_regex_async(w: MyWorldMut, step: String, #[step] ctx: &Step, num: usize) {
    assert_eq!(step, "foo");
    assert_eq!(num, 0);
    assert_eq!(ctx.value, "foo is 0");

    w.0.foo += 1;
}

#[given("{word} is sync {int}")]
fn test_regex_sync_slice(w: MyWorldMut, step: &Step, matches: &[String]) {
    assert_eq!(matches[0], "foo");
    assert_eq!(matches[1].parse::<usize>().unwrap(), 0);
    assert_eq!(step.value, "foo is sync 0");

    w.0.foo += 1;
}

#[when("I write \"{word}\" to '{word}'")]
fn test_return_result_write(w: MyWorldMut, what: String, filename: String) -> io::Result<()> {
    let mut path = w.0.dir.path().to_path_buf();
    path.push(filename);
    fs::write(path, what)
}

#[then("the file {string} should contain {string}")]
fn test_return_result_read(w: MyWorldRef, inputs: &[String]) {
    let mut path = w.0.dir.path().to_path_buf();
    path.push(inputs[0].clone());

    let content = fs::read_to_string(path).expect("Failed to read file");
    assert_eq!(content, inputs[1]);
}

#[then("{string} contains {string}")]
fn test_return_result_read_slice(w: MyWorldRef, inputs: &[String]) {
    let mut path = w.0.dir.path().to_path_buf();
    path.push(inputs[0].clone());

    let content = fs::read_to_string(path).expect("Failed to read file");
    assert_eq!(content, inputs[1]);
}

#[then("the word {word} is seen")]
fn test_then_assert_outcome(_w: MyWorldRef, word: String) -> AssertOutcome<()> {
    if word == "ok" {
        AssertOutcome::Passed(())
    } else {
        AssertOutcome::failed(format!("unexpected word: {}", word))
    }
}

#[tokio::main]
async fn main() {
    let features = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/features");

    let writer = MyWorld::namako()
        .max_concurrent_scenarios(None)
        .fail_on_skipped()
        .run(features)
        .await;

    assert_eq!(writer.failed_steps(), 1);
}
