use std::{cell::Cell, fs, io::Read as _};

use namako_engine::{
    World as _, WriterExt as _, cli,
    given, then, when, writer,
};
use regex::Regex;
use tempfile::NamedTempFile;

// Context wrapper types (StepContext impls auto-generated by #[derive(World)])
struct WorldMut<'a>(&'a mut World);

#[derive(Clone, Copy)]
struct WorldRef<'a>(&'a World);

impl<'a> WorldMut<'a> { fn new(world: &'a mut World) -> Self { Self(world) } }
impl<'a> WorldRef<'a> { fn new(world: &'a World) -> Self { Self(world) } }

#[given("{int} sec(s)")]
#[when("{int} sec(s)")]
fn step(world: WorldMut) {
    let new_val = world.0.0.get() + 1;
    world.0.0.set(new_val);
    assert!(new_val < 4, "Too much!");
}

#[then("{int} sec(s)")]
fn then_step(world: WorldRef) {
    // Then step also increments to match original test behavior
    let new_val = world.0.0.get() + 1;
    world.0.0.set(new_val);
    assert!(new_val < 4, "Too much!");
}

#[tokio::test]
async fn output() {
    let mut file = NamedTempFile::new().unwrap();
    drop(
        World::namako()
            .with_writer(
                writer::Libtest::new(file.reopen().unwrap()).normalized(),
            )
            .fail_on_skipped()
            .with_default_cli()
            .run("tests/features/wait")
            .await,
    );

    let mut buffer = String::new();
    file.read_to_string(&mut buffer).unwrap();

    // Required to strip out non-deterministic parts of output, so we could
    // compare them well.
    let non_deterministic = Regex::new(
        "\":[+-]?\\d+(\\.\\d+)?([eE][+-]?\\d+)?\
         |([^\"\\n\\s]*)[/\\\\]([A-z1-9-_]*)\\.(feature|rs)(:\\d+:\\d+)?\
         |\\s?\n",
    )
    .unwrap();

    assert_eq!(
        non_deterministic.replace_all(&buffer, ""),
        non_deterministic.replace_all(
            &fs::read_to_string("tests/libtest/correct.stdout").unwrap(),
            "",
        ),
    );
}

#[tokio::test]
async fn output_report_time() {
    let mut cli = cli::Opts::<_, _, writer::libtest::Cli>::default();
    cli.writer.report_time = Some(writer::libtest::ReportTime::Plain);
    let mut file = NamedTempFile::new().unwrap();
    drop(
        World::namako()
            .with_writer(
                writer::Libtest::new(file.reopen().unwrap()).normalized(),
            )
            .fail_on_skipped()
            .with_cli(cli)
            .run("tests/features/wait")
            .await,
    );

    let mut buffer = String::new();
    file.read_to_string(&mut buffer).unwrap();

    // Required to strip out non-deterministic parts of output, so we could
    // compare them well.
    let non_deterministic = Regex::new(
        "\":[+-]?\\d+(\\.\\d+)?([eE][+-]?\\d+)?\
         |([^\"\\n\\s]*)[/\\\\]([A-z1-9-_]*)\\.(feature|rs)(:\\d+:\\d+)?\
         |\\s?\n",
    )
    .unwrap();

    assert_eq!(
        non_deterministic.replace_all(&buffer, ""),
        non_deterministic.replace_all(
            &fs::read_to_string("tests/libtest/correct-report-time.stdout")
                .unwrap(),
            "",
        ),
    );
}

#[derive(Clone, Default, namako_engine::World)]
#[world(mut_ctx = WorldMut<'a>, ref_ctx = WorldRef<'a>)]
struct World(Cell<usize>);

impl std::fmt::Debug for World {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("World").field(&self.0.get()).finish()
    }
}
