use std::{borrow::Cow, fmt::Debug, mem, sync::LazyLock, cell::RefCell};

use namako_engine::{
    Event, Writer, cli, event,
    given, parser, then, when,
};
use regex::Regex;

// Context wrapper types (StepContext impls auto-generated by #[derive(World)])
struct WorldMut<'a>(&'a mut World);

#[derive(Clone, Copy)]
struct WorldRef<'a>(&'a World);

impl<'a> WorldMut<'a> { fn new(world: &'a mut World) -> Self { Self(world) } }
impl<'a> WorldRef<'a> { fn new(world: &'a World) -> Self { Self(world) } }

#[derive(Debug, Default, namako::World)]
#[world(mut_ctx = WorldMut<'a>, ref_ctx = WorldRef<'a>)]
struct World(RefCell<usize>);

#[given("foo is {int}")]
#[given("foo is {int} ambiguous")]
#[when("foo is {int}")]
fn step(w: WorldMut, num: usize) {
    check_and_inc(w.0, num);
}

#[then("foo is {int}")]
fn then_step(w: WorldRef, num: usize) {
    check_and_inc(w.0, num);
}

fn check_and_inc(w: &World, num: usize) {
    let mut val = w.0.borrow_mut();
    assert_eq!(*val, num);
    *val += 1;
}

#[given("foo is {int} ambiguous")]
fn ambiguous(_w: WorldMut, _num: usize) {}

#[derive(Default)]
struct DebugWriter {
    output: String,
    first_line_printed: bool,
}

impl<World: 'static + Debug> Writer<World> for DebugWriter {
    type Cli = cli::Empty;

    async fn handle_event(
        &mut self,
        ev: parser::Result<Event<event::Namako<World>>>,
        _: &Self::Cli,
    ) {
        let ev: Cow<_> = match ev.map(Event::into_inner) {
            Err(_) => "ParsingError".into(),
            Ok(ev) => format!("{ev:?}").into(),
        };

        let without_span = SPAN_OR_PATH_RE.replace_all(ev.as_ref(), "");

        if mem::replace(&mut self.first_line_printed, true) {
            self.output.push('\n');
        }
        self.output.push_str(without_span.as_ref());
    }
}

/// [`Regex`] to unify spans and file paths on Windows, Linux and macOS for
/// tests.
// TODO: Switch back to `lazy-regex::regex!()` once it migrates to `std`:
//       https://github.com/Canop/lazy-regex/issues/10
static SPAN_OR_PATH_RE: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(
        "( span: Span \\{ start: (\\d+), end: (\\d+) },\
         |, col: (\\d+)\
         | path: (None|(Some\\()?\"[^\"]*\")\\)?,?)",
    )
    .unwrap()
});

#[cfg(test)]
mod spec {
    use std::{fmt, fs, io, sync::LazyLock};

    use namako_engine::{
        World as _, WriterExt as _,
        writer::{self, Coloring},
    };
    use globwalk::GlobWalkerBuilder;
    use itertools::Itertools;
    use regex::{Captures, Match, Regex};

    use super::{DebugWriter, World};

    /// [`Regex`] to transform full paths (both unix-like and windows) to a
    /// relative paths.
    // TODO: Switch back to `lazy-regex::regex!()` once it migrates to `std`:
    //       https://github.com/Canop/lazy-regex/issues/10
    static FULL_PATH: LazyLock<Regex> = LazyLock::new(|| {
        Regex::new(r"((\?|\\|\/).*(\\|\/))?tests((\\|\/)\w*)*").unwrap()
    });

    /// Replaces [`FULL_PATH`] with a relative path.
    fn relative_path(cap: &Captures<'_>) -> String {
        format!(
            "tests{}",
            cap[0].split("tests").skip(1).join("tests").replace('\\', "/")
        )
    }

    /// [`Regex`] to make `cargo careful` assertion output to match `cargo test`
    /// output.
    // TODO: Switch back to `lazy-regex::regex!()` once it migrates to `std`:
    //       https://github.com/Canop/lazy-regex/issues/10
    static CAREFUL_ASSERTION: LazyLock<Regex> = LazyLock::new(|| {
        Regex::new(
            "assertion `left == right` failed(:)?\
             (.*)\
             \n(\\s+)left: (.+)\
             \n(\\s+)right: (\\w+)",
        )
        .unwrap()
    });

    /// Replaces [`CAREFUL_ASSERTION`] with `cargo test` output.
    fn unify_asserts(cap: &Captures<'_>) -> String {
        format!(
            "assertion failed: `(left == right)`{}\
             {}\
             \n{}left: `{}`,\
             \n{}right: `{}`",
            cap.get(1).as_ref().map_or("", Match::as_str),
            &cap[2],
            &cap[3],
            &cap[4],
            &cap[5],
            &cap[6],
        )
    }

    /// Deterministic output of a [`writer::Basic`].
    #[derive(Clone, Debug, Default)]
    struct Output(Vec<u8>);

    impl io::Write for Output {
        fn write(&mut self, buf: &[u8]) -> io::Result<usize> {
            self.0.extend_from_slice(buf);
            Ok(buf.len())
        }

        fn flush(&mut self) -> io::Result<()> {
            Ok(())
        }
    }

    impl fmt::Display for Output {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            let o = String::from_utf8(self.0.clone())
                .unwrap_or_else(|e| panic!("`Output` is not a string: {e}"));
            let o = CAREFUL_ASSERTION.replace_all(&o, unify_asserts);
            let o = FULL_PATH.replace_all(&o, relative_path);
            write!(f, "{o}")
        }
    }

    #[tokio::test]
    async fn test() {
        let walker =
            GlobWalkerBuilder::new("tests/features/output", "*.feature")
                .case_insensitive(true)
                .build()
                .unwrap();
        let files = walker
            .filter_map(Result::ok)
            .map(|entry| entry.file_name().to_str().unwrap().to_owned())
            .collect::<Vec<String>>();

        assert_eq!(
            files.len(),
            fs::read_dir("tests/features/output").unwrap().count() / 4,
            "Not all `.feature` files were collected",
        );

        for file in files {
            let debug = World::namako()
                .with_writer(DebugWriter::default().normalized())
                .with_default_cli()
                .run(format!("tests/features/output/{file}"))
                .await;
            fs::write(
                format!("tests/features/output/{file}.debug.out"),
                debug.output.trim(),
            )
            .unwrap();

            let mut output = Output::default();
            _ = World::namako()
                .with_writer(
                    writer::Basic::raw(&mut output, Coloring::Never, 0)
                        .discard_stats_writes()
                        .normalized(),
                )
                .with_default_cli()
                .run(format!("tests/features/output/{file}"))
                .await;
            fs::write(
                format!("tests/features/output/{file}.basic.out"),
                output.to_string().trim(),
            )
            .unwrap();

            let mut output = Output::default();
            _ = World::namako()
                .with_writer(
                    writer::Basic::raw(&mut output, Coloring::Always, 0)
                        .discard_stats_writes()
                        .normalized(),
                )
                .with_default_cli()
                .run(format!("tests/features/output/{file}"))
                .await;
            fs::write(
                format!("tests/features/output/{file}.colored.out"),
                output.to_string().trim(),
            )
            .unwrap();
        }
    }
}
