

//! Helper type-level glue for [`namako_codegen`] crate.

use std::convert::Infallible;

pub use anyhow;
pub use cucumber_expressions::{
    Expression, Spanned, expand::parameters::Provider as ParametersProvider,
};
use futures::future;
pub use futures::future::LocalBoxFuture;
pub use inventory::{self, collect, submit};
pub use regex::Regex;

use crate::{Step, World, step};

// =============================================================================
// Context-First ABI Support
// =============================================================================

/// Trait implemented by step context types to link back to their World.
///
/// This trait is used by the codegen to determine which World type a step
/// function belongs to, based on the context type in its first argument.
///
/// **Note:** When using `#[derive(World)]` with `mut_ctx` and `ref_ctx` attributes,
/// the `StepContext` impls are auto-generated. Manual implementation is only
/// needed for advanced cases like manual `impl World` for custom polling.
///
/// # Auto-Generated Example
///
/// ```ignore
/// // StepContext impl is auto-generated by #[derive(World)]
/// #[derive(Default, World)]
/// #[world(mut_ctx = MyWorldMut<'a>, ref_ctx = MyWorldRef<'a>)]
/// struct MyWorld;
///
/// struct MyWorldMut<'a>(&'a mut MyWorld);
/// struct MyWorldRef<'a>(&'a MyWorld);
///
/// impl<'a> MyWorldMut<'a> { fn new(w: &'a mut MyWorld) -> Self { Self(w) } }
/// impl<'a> MyWorldRef<'a> { fn new(w: &'a MyWorld) -> Self { Self(w) } }
/// // StepContext impls are generated automatically!
/// ```
pub trait StepContext {
    /// The World type that this context is derived from.
    type World: World;
}

// =============================================================================
// Then Step Assertion Support
// =============================================================================

/// Result of a Then-step assertion.
///
/// Worlds use this to control assertion semantics:
/// - Simple worlds: run once, `Pending` = error
/// - Polling worlds: retry on `Pending` until `Passed` or timeout
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AssertOutcome<T = ()> {
    /// Assertion passed with a value.
    Passed(T),
    /// Not yet satisfied — World may retry.
    Pending,
    /// Permanently failed with an error message.
    Failed(String),
}

impl<T> AssertOutcome<T> {
    /// Returns `true` if the outcome is `Passed`.
    #[inline]
    pub fn is_passed(&self) -> bool {
        matches!(self, Self::Passed(_))
    }

    /// Returns `true` if the outcome is `Pending`.
    #[inline]
    pub fn is_pending(&self) -> bool {
        matches!(self, Self::Pending)
    }

    /// Convenience constructor for `Passed(())`.
    #[inline]
    pub fn passed() -> AssertOutcome<()> {
        AssertOutcome::Passed(())
    }

    /// Convenience constructor for `Pending`.
    #[inline]
    pub fn pending() -> Self {
        Self::Pending
    }

    /// Convenience constructor for `Failed`.
    #[inline]
    pub fn failed(msg: impl Into<String>) -> Self {
        Self::Failed(msg.into())
    }
}

// =============================================================================
// NPAP v1 Metadata
// =============================================================================

/// NPAP v1 binding metadata collected at compile time.
///
/// This struct contains all the information needed for the semantic step
/// registry per GOLD_PLAN.md §6.2.1.
#[derive(Debug, Clone, Copy)]
pub struct NpapBindingMetadata {
    /// Binding ID computed from (kind + expression) per §4.2.1.
    pub binding_id: &'static str,
    /// The cucumber expression string.
    pub expression: &'static str,
    /// Step kind: "Given", "When", or "Then".
    pub kind: &'static str,
    /// Implementation hash for drift detection per §6.2.2.
    pub impl_hash: &'static str,
    /// Number of capture parameters per §4.4.2.
    pub captures_arity: u32,
    /// Whether binding accepts a DocString per §4.4.3.
    pub accepts_docstring: bool,
    /// Whether binding accepts a DataTable per §4.4.4.
    pub accepts_datatable: bool,
}

// =============================================================================
// World Inventory
// =============================================================================

/// [`World`] extension allowing to register steps in [`inventory`].
pub trait WorldInventory: World {
    /// Struct [`submit`]ted in a [`given`] macro.
    ///
    /// [`given`]: crate::given
    type Given: inventory::Collect + StepConstructor<Self>;

    /// Struct [`submit`]ted in a [`when`] macro.
    ///
    /// [`when`]: crate::when
    type When: inventory::Collect + StepConstructor<Self>;

    /// Struct [`submit`]ted in a [`then`] macro.
    ///
    /// [`then`]: crate::then
    type Then: inventory::Collect + StepConstructor<Self>;
}

/// Alias for a [`fn`] returning a [`Regex`].
pub type LazyRegex = fn() -> Regex;

/// Trait for registering a [`Step`] with [`given`], [`when`] and [`then`]
/// attributes inside [`World::collection()`] method.
///
/// [`given`]: crate::given
/// [`when`]: crate::when
/// [`then`]: crate::then
pub trait StepConstructor<W> {
    /// Returns an inner [`Step`] with the corresponding [`Regex`].
    fn inner(&self) -> (step::Location, LazyRegex, Step<W>);

    /// Returns NPAP v1 binding metadata for semantic registry export.
    fn npap_metadata(&self) -> NpapBindingMetadata;
}

/// Custom parameter of a [Cucumber Expression].
///
/// Should be implemented only with via [`Parameter`] derive macro.
///
/// [`Parameter`]: macro@crate::Parameter
/// [Cucumber Expression]: https://namako.github.io/cucumber-expressions
pub trait Parameter {
    /// [`Regex`] matching this [`Parameter`].
    ///
    /// Shouldn't contain any capturing groups.
    ///
    /// Validated during [`Parameter`](macro@crate::Parameter) derive macro
    /// expansion.
    const REGEX: &'static str;

    /// Name of this [`Parameter`] to be referenced by in
    /// [Cucumber Expressions].
    ///
    /// [Cucumber Expressions]: https://namako.github.io/cucumber-expressions
    const NAME: &'static str;
}

/// Compares two strings in a `const` context.
///
/// As there is no `const impl Trait` and `l == r` calls [`Eq`], we have to use
/// a custom comparison function.
///
/// [`Eq`]: std::cmp::Eq
// TODO: Remove once `Eq` trait is allowed in a `const` context.
#[must_use]
pub const fn str_eq(l: &str, r: &str) -> bool {
    if l.len() != r.len() {
        return false;
    }

    let (l, r) = (l.as_bytes(), r.as_bytes());
    let mut i = 0;
    while i < l.len() {
        if l[i] != r[i] {
            return false;
        }
        i += 1;
    }

    true
}

/// Return-type polymorphism over `async`ness for a `#[world(init)]` attribute
/// of a [`#[derive(World)]`](macro@World) macro.
///
/// It allows to accept both sync and `async` functions as an attribute's
/// argument, by automatically wrapping sync functions in a [`future::Ready`].
///
/// ```rust
/// # #[derive(Default)]
/// # struct World;
/// #
/// impl namako::World for World {
///     type Error = anyhow::Error;
///     type MutCtx<'a> = &'a mut Self;
///     type RefCtx<'a> = &'a Self;
///
///     fn ctx_mut(&mut self) -> Self::MutCtx<'_> { self }
///     fn ctx_ref(&mut self) -> Self::RefCtx<'_> { self }
///
///     async fn new() -> Result<Self, Self::Error> {
///         use namako::codegen::{
///             IntoWorldResult as _, ToWorldFuture as _,
///         };
///
///         fn as_fn_ptr<T>(v: fn() -> T) -> fn() -> T {
///             v
///         }
///
///         //           `#[world(init)]`'s value
///         //          ⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄
///         (&as_fn_ptr(<Self as Default>::default))
///             .to_world_future() // maybe wraps into `future::Ready`
///             .await
///             .into_world_result()
///             .map_err(Into::into)
///     }
/// }
/// ```
pub trait ToWorldFuture {
    /// [`Future`] returned by this [`World`] constructor.
    ///
    /// Set to [`future::Ready`] in case construction is sync.
    type Future: Future;

    /// Resolves this [`Future`] for constructing a new[`World`] using
    /// [autoderef-based specialization][0].
    ///
    /// [0]: https://tinyurl.com/autoref-spec
    fn to_world_future(&self) -> Self::Future;
}

impl<R: IntoWorldResult> ToWorldFuture for fn() -> R {
    type Future = future::Ready<R>;

    fn to_world_future(&self) -> Self::Future {
        future::ready(self())
    }
}

impl<Fut: Future> ToWorldFuture for &fn() -> Fut
where
    Fut::Output: IntoWorldResult,
{
    type Future = Fut;

    fn to_world_future(&self) -> Self::Future {
        self()
    }
}

/// Return-type polymorphism over fallibility for a `#[world(init)]` attribute
/// of a [`#[derive(World)]`](macro@World) macro.
///
/// It allows to accept both fallible (returning [`Result`]) and infallible
/// functions as an attribute's argument, by automatically wrapping infallible
/// functions in a [`Result`]`<`[`World`]`, `[`Infallible`]`>`.
///
/// ```rust
/// # #[derive(Default)]
/// # struct World;
/// #
/// impl namako::World for World {
///     type Error = anyhow::Error;
///     type MutCtx<'a> = &'a mut Self;
///     type RefCtx<'a> = &'a Self;
///
///     fn ctx_mut(&mut self) -> Self::MutCtx<'_> { self }
///     fn ctx_ref(&mut self) -> Self::RefCtx<'_> { self }
///
///     async fn new() -> Result<Self, Self::Error> {
///         use namako::codegen::{
///             IntoWorldResult as _, ToWorldFuture as _,
///         };
///
///         fn as_fn_ptr<T>(v: fn() -> T) -> fn() -> T {
///             v
///         }
///
///         //           `#[world(init)]`'s value
///         //          ⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄
///         (&as_fn_ptr(<Self as Default>::default))
///             .to_world_future()
///             .await
///             .into_world_result() // maybe wraps into `Result<_, Infallible>`
///             .map_err(Into::into)
///     }
/// }
/// ```
pub trait IntoWorldResult: Sized {
    /// [`World`] type itself.
    type World: World;

    /// Error returned by this [`World`] constructor.
    ///
    /// Set to [`Infallible`] in case construction is infallible.
    type Error;

    /// Passes [`Result`]`<`[`World`]`, Self::Error>` as is, or wraps the plain
    /// [`World`] in a [`Result`]`<`[`World`]`, `[`Infallible`]`>`.
    ///
    /// # Errors
    ///
    /// In case the [`World`] construction errors.
    fn into_world_result(self) -> Result<Self::World, Self::Error>;
}

impl<W: World> IntoWorldResult for W {
    type World = Self;
    type Error = Infallible;

    fn into_world_result(self) -> Result<Self, Self::Error> {
        Ok(self)
    }
}

impl<W: World, E> IntoWorldResult for Result<W, E> {
    type World = W;
    type Error = E;

    fn into_world_result(self) -> Self {
        self
    }
}
